name: LFTP sync
description: Sync data using lftp
version: 0.1.0
slug: lftp-conf
url: https://github.com/ElVit/hassio-addons/lftp-conf
startup: once
init: false
boot: manual
hassio_role: default
hassio_api: true
homeassistant_api: true
stage: experimental
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - addons:rw
  - backup:rw
  - config:rw
  - media:rw
  - share:rw
  - ssl:rw
options:
  script_dir: /config/addons-config/lftp
  credentials:
    - url: 192.168.100.100
      username: dummyUser
      password: null
schema:
  script_dir: str
  credentials:
    - url: str
      username: str
      password: password
