name: LFTP sync - DIY
description: Sync data using lftp
version: 0.3.0
slug: lftp-diy
url: https://github.com/ElVit/hassio-addons/lftp-diy
startup: application
boot: auto
homeassistant_api: true
hassio_api: true
stdin: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - addons:rw
  - backup:rw
  - config:rw
  - media:rw
  - share:rw
  - ssl:rw
options:
  host: "ftp://192.168.1.1"
  username: user
  password: null
  remote_folder: "/remoteDir"
  local_folder: "/share/localDir"
  direction: download
  parallel: no
  copy_hidden_files: false
  auto_confirm: true
  no_certificate_check: true
  delete: true
  verbose: true
  continue: true
  dry_run: true
schema:
  host: str
  username: str
  password: password
  remote_folder: str
  local_folder: str
  direction: list(download|upload)
  parallel: list(no|many-small-files|few-large-files)
  copy_hidden_files: bool
  exclude_glob:
    - str
  auto_confirm: bool
  no_certificate_check: bool
  delete: bool
  verbose: bool
  continue: bool
  dry_run: bool
  script_file: "str?"
