name: Netatalk share
description: Expose Home Assistant folders with AFP
version: 0.1.0
slug: netatalk-mod
url: https://github.com/ElVit/hassio-addons/netatalk-mod
startup: services
init: false
boot: auto
hassio_role: default
hassio_api: true
host_network: true
host_dbus: true
host_ipc: true
apparmor: true
udev: true
# devicetree: true
journald: true
stage: experimental
ports:
  548/tcp: 548
ports_description:
  548/tcp: AFP
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - addons:rw
  - backup:rw
  - config:rw
  - media:rw
  - share:rw
  - ssl:rw
options:
  logins:
    - username: homeassistant
      password: null
  config_dir: /config/addons-config/netatalk
schema:
  logins:
    - username: str
      password: password
  config_dir: str
