name: Samba config
description: Expose Home Assistant folders with SMB/CIFS
version: 0.1.0
slug: samba-conf
url: https://github.com/ElVit/hassio-addons/samba-conf
startup: services
init: false
boot: auto
hassio_role: default
hassio_api: true
host_network: true
stage: experimental
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - addons:rw
  - backup:rw
  - config:rw
  - media:rw
  - share:rw
  - ssl:rw
options:
  config_dir: /config/addons-config/samba
  logins:
    - username: dummyUser
      password: null
schema:
  config_dir: str
  logins:
    - username: str
      password: password
