name: Traefik
version: 1.1.0
slug: traefik
description: Traefik is a modern HTTP reverse proxy and load balancer that makes deploying microservices easy.
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: system
init: false
stage: stable
boot: auto
url: https://github.com/ElVit/hassio-addons/traefik
ports:
  80/tcp: 80
  443/tcp: 443
ports_description:
  80/tcp: HTTP
  443/tcp: HTTPS
ingress: true
ingress_entry: dashboard/
hassio_role: default
hassio_api: true
panel_icon: mdi:earth-arrow-right
map:
  - config:rw
  - share:rw
  - ssl:rw
options:
  custom_static_config: false
  dir_of_dynamic_config: /config/addons-config/traefik
  log_level: info
  access_logs: false
  forwarded_headers_insecure: false
  letsencrypt:
    enabled: false
    resolvers: []
  env_vars: []
schema:
  custom_static_config: bool
  dir_of_static_config: str?
  dir_of_dynamic_config: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  access_logs: bool
  forwarded_headers_insecure: bool
  letsencrypt:
    enabled: bool
    email: email?
    challenge_type: match(tlsChallenge|httpChallenge|dnsChallenge)?
    provider: str?
    delayBeforeCheck: int?
    resolvers:
      - str?
  env_vars:
    - str
