name: Rsync daemon
description: Sync folders with rsync daemon
version: 1.0.0-beta.1
slug: rsyncd
url: https://github.com/ElVit/hassio-addons/tree/main/rsync
init: false
host_network: true
startup: services
stdin: true
stage: experimental
codenotary: notary@home-assistant.io
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - addon_config:rw
  - all_addon_configs:rw
  - homeassistant_config:rw
  - addons:rw
  - backup:rw
  - media:rw
  - share:rw
  - ssl:rw
schema:
  rsync_commands:
    - str?
options:
  rsync_commands: []
