name: Rsync daemon
description: Sync folders with rsync daemon
url: https://github.com/ElVit/hassio-addons/tree/main/rsync
version: 1.0.0-beta.1
stage: experimental
slug: rsync
codenotary: notary@home-assistant.io
startup: services
init: false
boot: auto
hassio_role: default
hassio_api: true
host_network: true
stdin: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - addon_config:rw
  - all_addon_configs:rw
  - homeassistant_config:rw
  - addons:rw
  - backup:rw
  - media:rw
  - share:rw
  - ssl:rw
schema:
  rsync_commands:
    - str?
options:
  rsync_commands: []
