name: Netatalk share - diy
description: Expose Home Assistant folders with AFP
version: 0.0.25
slug: netatalk-diy
url: https://github.com/ElVit/hassio-addons/netatalk-diy
startup: services
init: false
hassio_api: true
host_network: true
ports:
  548/tcp: 548
ports_description:
  548/tcp: AFP
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - addons:rw
  - backup:rw
  - config:rw
  - media:rw
  - share:rw
  - ssl:rw
options:
  username: test
  password: null
  spotlight: true
  zeroconf: true
schema:
  username: str
  password: password
  spotlight: bool
  zeroconf: bool
