name: Netatalk share - DIY
description: Expose Home Assistant folders with AFP
version: 0.0.51
slug: netatalk-diy
url: https://github.com/ElVit/hassio-addons/netatalk-diy
startup: services
init: false
hassio_role: default
hassio_api: true
host_network: true
ports:
  548/tcp: 548
ports_description:
  548/tcp: AFP
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - addons:rw
  - backup:rw
  - config:rw
  - media:rw
  - share:rw
  - ssl:rw
options:
  username: testuser
  password: null
  config_dir: /config/addons-config/netatalk
  netatalk_share_dir: /share/netatalk_share
  timemachine_dir: /share/timemachine
schema:
  username: str
  password: password
  config_dir: str
  netatalk_share_dir: str
  timemachine_dir: str
