name: Samba share - DIY
description: Expose Home Assistant folders with SMB/CIFS
version: 0.0.19
slug: samba-diy
url: https://github.com/ElVit/hassio-addons/samba-diy
startup: services
init: false
hassio_api: true
host_network: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - addons:rw
  - backup:rw
  - config:rw
  - media:rw
  - share:rw
  - ssl:rw
options:
  workgroup: WORKGROUP
  logins:
    - username: testuser
      password: null
  config_dir: /config/addons-config/samba
schema:
  workgroup: str
  logins:
    - username: str
      password: password
  config_dir: str
