name: Samba share - diy
description: Expose Home Assistant folders with SMB/CIFS
version: 9.5.1
slug: samba-diy
url: https://github.com/ElVit/hassio-addons/samba-diy
startup: services
init: false
hassio_api: true
host_network: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - addons:rw
  - backup:rw
  - config:rw
  - media:rw
  - share:rw
  - ssl:rw
options:
  workgroup: WORKGROUP
  logins:
    - username: user1
      password: password1
  allow_hosts:
    - "10.0.0.0/8"
    - "172.16.0.0/12"
    - "192.168.0.0/16"
    - "fe80::/10"
  veto_files:
    - "._*"
    - ".DS_Store"
    - "Thumbs.db"
    - "icon?"
    - ".Trashes"
  compatibility_mode: false
schema:
  workgroup: str
  logins:
    - username: str
      password: str
  allow_hosts:
    - str
  veto_files:
    - str
  compatibility_mode: bool
