name: Samba share
description: Expose Home Assistant folders with SMB/CIFS
version: 0.1.0
slug: samba-mod
url: https://github.com/ElVit/hassio-addons/samba-mod
startup: services
init: false
hassio_role: default
hassio_api: true
host_network: true
stage: experimental
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - addons:rw
  - backup:rw
  - config:rw
  - media:rw
  - share:rw
  - ssl:rw
options:
  logins:
    - username: homeassistant
      password: null
  config_dir: /config/addons-config/samba
schema:
  logins:
    - username: str
      password: password
  config_dir: str
