name: LFTP sync
description: Sync data using lftp
version: 0.1.0
slug: lftp-mod
url: https://github.com/ElVit/hassio-addons/lftp-mod
startup: once
init: false
boot: auto
hassio_role: default
hassio_api: true
homeassistant_api: true
stdin: true
stage: experimental
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - addons:rw
  - backup:rw
  - config:rw
  - media:rw
  - share:rw
  - ssl:rw
options:
  username: homeassistant
  password: null
  script_dir: "/config/addons-config/lftp"
schema:
  username: str
  password: password
  script_dir: str
